const ACTIONSNAME = {
  // TOAST
  TOAST_OPEN: 'TOAST_OPEN',
  TOAST_CLOSE: 'TOAST_CLOSE',

  // LOGIN
  LOGIN_RESET: 'LOGIN_RESET',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  // USERS
  USERS_RESET: 'USERS_RESET',

  USERS_REQUEST: 'USERS_REQUEST',
  USERS_SUCCESS: 'USERS_SUCCESS',
  USERS_FAILURE: 'USERS_FAILURE',
};

export default ACTIONSNAME;
